// 타임라인 이벤트 상세 모달의 UI 빌더 함수 모음
// 헤더, 시간 범위, 메모, 안내 메시지, 편집 버튼 등 개별 섹션을 구성한다
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../../core/theme/radius_tokens.dart';
import '../../../../core/theme/spacing_tokens.dart';
import '../../../../core/theme/theme_colors.dart';
import '../../../../core/theme/typography_tokens.dart';
import '../../../../shared/models/todo.dart';
import 'timeline_event_edit_dialog.dart';

/// 모달 헤더: 컬러 바 + 타이틀 + 유형 뱃지
Widget buildDetailsHeader(
  BuildContext context,
  Todo todo,
  Color color,
  String typeLabel,
) {
  return Row(
    children: [
      Container(
        width: 4,
        height: 24,
        decoration: BoxDecoration(
          color: color,
          borderRadius: BorderRadius.circular(AppRadius.sm),
        ),
      ),
      const SizedBox(width: AppSpacing.md),
      Expanded(
        child: Text(
          todo.title,
          style: AppTypography.titleMd.copyWith(
            color: context.themeColors.textPrimary,
          ),
        ),
      ),
      Container(
        padding: const EdgeInsets.symmetric(
          horizontal: AppSpacing.md,
          vertical: AppSpacing.xxs,
        ),
        decoration: BoxDecoration(
          color: color.withValues(alpha: 0.15),
          borderRadius: BorderRadius.circular(AppRadius.xl),
        ),
        child: Text(
          typeLabel,
          style: AppTypography.captionMd.copyWith(
            color: color,
            fontWeight: AppTypography.weightSemiBold,
          ),
        ),
      ),
    ],
  );
}

/// 시간 범위 행
Widget buildTimeRange(
  BuildContext context,
  String timeRangeStr,
  String? durationStr,
) {
  return Row(
    children: [
      Icon(
        Icons.access_time_rounded,
        size: 16,
        color: context.themeColors.textPrimaryWithAlpha(0.6),
      ),
      const SizedBox(width: AppSpacing.sm),
      // Flexible로 감싸 시간 범위 텍스트의 오버플로를 방지한다
      Flexible(
        child: Text(
          timeRangeStr,
          style: AppTypography.bodyMd.copyWith(
            color: context.themeColors.textPrimaryWithAlpha(0.8),
          ),
          overflow: TextOverflow.ellipsis,
          maxLines: 1,
        ),
      ),
      if (durationStr != null) ...[
        const SizedBox(width: AppSpacing.md),
        Text(
          '($durationStr)',
          style: AppTypography.captionMd.copyWith(
            color: context.themeColors.textPrimaryWithAlpha(0.5),
          ),
        ),
      ],
    ],
  );
}

/// 메모 텍스트
Widget buildMemo(BuildContext context, String memo) {
  return Text(
    memo,
    style: AppTypography.bodyMd.copyWith(
      color: context.themeColors.textPrimaryWithAlpha(0.7),
    ),
    maxLines: 3,
    overflow: TextOverflow.ellipsis,
  );
}

/// 자동 생성 항목 안내 메시지
Widget buildAutoMessage(BuildContext context, String message) {
  return Row(
    children: [
      Icon(
        Icons.info_outline_rounded,
        size: 16,
        color: context.themeColors.textPrimaryWithAlpha(0.5),
      ),
      const SizedBox(width: AppSpacing.sm),
      // Expanded로 감싸 긴 안내 메시지의 오버플로를 방지한다
      Expanded(
        child: Text(
          message,
          style: AppTypography.captionMd.copyWith(
            color: context.themeColors.textPrimaryWithAlpha(0.5),
          ),
          overflow: TextOverflow.ellipsis,
          maxLines: 1,
        ),
      ),
    ],
  );
}

/// 편집 버튼
Widget buildEditButton(
  BuildContext sheetCtx,
  BuildContext parentCtx,
  WidgetRef ref,
  Todo todo,
  Color color,
) {
  return SizedBox(
    width: double.infinity,
    child: TextButton.icon(
      onPressed: () {
        Navigator.of(sheetCtx).pop();
        openTimelineEditDialog(parentCtx, ref, todo);
      },
      icon: const Icon(Icons.edit_rounded, size: 18),
      label: const Text('편집'),
      style: TextButton.styleFrom(
        foregroundColor: color,
        padding: const EdgeInsets.symmetric(vertical: AppSpacing.mdLg),
      ),
    ),
  );
}

/// 자동 생성 안내 메시지를 반환한다
String? getAutoGeneratedMessage(Todo todo) {
  if (todo.id.startsWith('routine_')) return '자동 생성된 루틴입니다';
  if (todo.id.startsWith('timer_')) return '포모도로 타이머 기록입니다';
  return null;
}
