// 타임라인 이벤트 상세 모달 — 바텀시트 표시 로직
// showTimelineEventDetails 함수가 상세 모달을 구성하여 표시한다
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../../core/theme/color_tokens.dart';
import '../../../../core/theme/radius_tokens.dart';
import '../../../../core/theme/spacing_tokens.dart';
import '../../../../core/theme/theme_colors.dart';
import '../../../../shared/models/todo.dart';
import 'timeline_event_details_builders.dart';
import 'timeline_format_helpers.dart';

/// 타임라인 이벤트의 상세 모달을 표시한다
void showTimelineEventDetails({
  required BuildContext context,
  required WidgetRef ref,
  required Todo todo,
}) {
  final color = ColorTokens.eventColor(todo.colorIndex);
  final startStr = formatTimeOfDay(todo.startTime);
  final endStr = formatTimeOfDay(todo.endTime);
  final timeRangeStr =
      endStr != null ? '$startStr ~ $endStr' : (startStr ?? '');
  final durationStr = formatDuration(todo.startTime, todo.endTime);
  final typeLabel = getTypeLabel(todo);
  final isEditable = !todo.id.startsWith('routine_') && !todo.id.startsWith('timer_');
  final autoMsg = getAutoGeneratedMessage(todo);

  showModalBottomSheet(
    context: context,
    backgroundColor: ColorTokens.transparent,
    builder: (ctx) => Container(
      padding: const EdgeInsets.all(AppSpacing.xxl),
      decoration: BoxDecoration(
        color: context.themeColors.dialogSurface,
        borderRadius: BorderRadius.vertical(
          top: Radius.circular(AppRadius.huge),
        ),
      ),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          buildDetailsHeader(context, todo, color, typeLabel),
          const SizedBox(height: AppSpacing.lg),
          if (timeRangeStr.isNotEmpty) ...[
            buildTimeRange(context, timeRangeStr, durationStr),
            const SizedBox(height: AppSpacing.md),
          ],
          if (todo.memo != null && todo.memo!.isNotEmpty) ...[
            buildMemo(context, todo.memo!),
            const SizedBox(height: AppSpacing.md),
          ],
          if (autoMsg != null) ...[
            buildAutoMessage(context, autoMsg),
            const SizedBox(height: AppSpacing.md),
          ],
          if (isEditable) ...[
            const SizedBox(height: AppSpacing.sm),
            buildEditButton(ctx, context, ref, todo, color),
          ],
          const SizedBox(height: AppSpacing.md),
        ],
      ),
    ),
  );
}
